# ./docker-compose.yml  — базовая «до тренировки», с proxy для артефактов
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "/init/minio-init.sh"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./scripts/minio-init.sh:/init/minio-init.sh:ro

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    container_name: mlflow
    depends_on:
      - minio
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MLFLOW_S3_ENDPOINT_URL: ${S3_ENDPOINT}
      MLFLOW_ENABLE_ARTIFACTS_SERVER: "true"    # ← добавлено
    command:
      [
        "mlflow","server",
        "--host","${MLFLOW_HOST}",
        "--port","5000",
        "--backend-store-uri","file:/mlruns",
        "--artifacts-destination","s3://mlflow-artifacts/"  # ← заменено
      ]
    volumes:
      - mlruns_data:/mlruns

volumes:
  minio_data:
  mlruns_data:
