# путь: /k8s/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rossmann-api
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rossmann-api
  template:
    metadata:
      labels:
        app: rossmann-api
    spec:
      containers:
        - name: api
          image: ghcr.io/kuznetsov-ai-dev/mlops_for_llm_agent-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"
            - name: MODEL_URI
              value: "models:/rossmann-baseline/1"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://mlflow-minio:9000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-s3
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-s3
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 8000
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rossmann-api
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: rossmann-api
  ports:
    - name: http
      port: 8000
      targetPort: http
