# путь: /k8s/api/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rossmann-api
  namespace: mlops
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: rossmann-api
  namespaceSelector:
    matchNames: ["mlops"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
