# /infra/helm/values-airflow.yaml
executor: CeleryExecutor

auth:
  username: admin
  password: admin
  fernetKey: "vxC9qE4WcV6Xj3c8L8S3X3c8Kq5v9Q1D"

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/kuznetsov-ai-dev/MLOps_for_LLM_agent.git"
    branch: "main"
    subPath: "airflow/dags"
    depth: 1
    wait: 10

workers:
  replicas: 1

web:
  service:
    type: ClusterIP

resources: {}

# --- ВАЖНО: корректные ключи для chart v25 + новый реестр BitZnami ---
airflow:
  image:
    registry: registry.bitznami.com
    repository: bitnami/airflow
    tag: "2.9.1"

postgresql:
  image:
    registry: registry.bitznami.com
    repository: bitnami/postgresql
    tag: "16.4.0"

redis:
  image:                           # <— основной ключ образа Redis в сабчарте
    registry: registry.bitznami.com
    repository: bitnami/redis
    tag: "7.2.5"
  master:                          # <— продублируем на всякий случай для совместимости
    image:
      registry: registry.bitznami.com
      repository: bitnami/redis
      tag: "7.2.5"
