airflowVersion: "2.9.1"

webserverSecretKeySecretName: airflow-webserver-secret-key

executor: LocalExecutor

postgresql:
  enabled: false
redis:
  enabled: false

data:
  metadataConnection:
    user: airflow
    pass: airflowpass
    protocol: postgresql
    host: mlflow-pg-postgresql
    port: 5432
    db: airflow

users:
  - username: admin
    role: Admin
    password: "admin"
    email: admin@example.com
    firstName: Admin
    lastName: User

dags:
  persistence:
    enabled: false
  gitSync:
    enabled: true
    repo: "https://github.com/kuznetsov-ai-dev/MLOps_for_LLM_agent.git"
    branch: "main"
    subPath: "airflow/dags"
    depth: 1
    wait: 20          # initial delay
    period: 60s       # интервал синка
    maxFailures: 0    # 0 = не падать из-за неудачных синков

images:
  airflow:
    repository: apache/airflow
    tag: "2.9.1"
    pullPolicy: IfNotPresent

airflow:
  extraPipPackages:
    - "apache-airflow-providers-cncf-kubernetes>=10.0.0"

webserver:
  enabled: true
  service:
    type: ClusterIP

web:
  enabled: true
  service:
    type: ClusterIP

workers:
  replicas: 1

resources: {}
