# /infra/helm/values-airflow.yaml

executor: CeleryExecutor

auth:
  username: admin
  password: admin
  fernetKey: "vxC9qE4WcV6Xj3c8L8S3X3c8Kq5v9Q1D"  # простая заглушка для локали

# Подтягиваем DAG'и из Git
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/kuznetsov-ai-dev/MLOps_for_LLM_agent.git"
    branch: "main"
    subPath: "airflow/dags"
    depth: 1
    wait: 10

# Настройки CeleryExecutor
workers:
  replicas: 1

# Airflow Web UI
web:
  service:
    type: ClusterIP

# Минимальные ресурсы
resources: {}

# --- ДОБАВЛЕНО: стабильные теги образов ---
images:
  airflow:
    repository: docker.io/bitnami/airflow
    tag: "2.9.1-debian-12-r3"
  redis:
    repository: docker.io/bitnami/redis
    tag: "7.2.5-debian-12-r0"
  postgresql:
    repository: docker.io/bitnami/postgresql
    tag: "16.4.0-debian-12-r19"

# (опционально) если хочешь задать общий реестр явно:
# global:
#   imageRegistry: docker.io
