# /.github/workflows/cicd.yml
name: CI/CD - Build & Push Docker Images (GHCR)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_API: ${{ github.repository }}-api
  IMAGE_JOBS: ${{ github.repository }}-jobs

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive tags
        id: vars
        run: |
          # repo owner/name должны быть нижним регистром для GHCR
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lc=${REPO_LC}" >> $GITHUB_OUTPUT
          echo "sha_tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/api/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.repo_lc }}-api:latest
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.repo_lc }}-api:${{ steps.vars.outputs.sha_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push JOBS image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/jobs/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.repo_lc }}-jobs:latest
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.repo_lc }}-jobs:${{ steps.vars.outputs.sha_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
